ejercicio4: ejercicio4.cpp Rectangulo.o
        g++ ejercicio4.cpp Rectangulo.o Coordenada.o  -o ejercicio4 
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
        g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
        g++ Coordenada.cpp -c
