Programa4-2: Programa4-2.cpp Rectangulo.o
	g++ Programa4-2.cpp Rectangulo.o Coordenada.o -o Programa4-2
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
