Programa4-3: Programa4-3.cpp Rectangulo.o
	g++ Programa4-3.cpp Rectangulo.o Coordenada.o -o Programa4-3
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
